config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
  devise_for :users
  resources :novels do
    resources :articles
  end  
  root to: "novels#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :novel
    def self.chapter_number( novel_id_number )
        # Detect latest novel number, then add new one.
        latest_chapter = Article.where( novel_id: novel_id_number ).count
        #byebug
        return latest_chapter + 1
    end
end

app/models/novel.rb
class Novel < ApplicationRecord
    #title author plot
    has_many :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
    def new
        @forms = Article.new
        @form_url = novel_articles_path
    end
    def create
        new_article = Article.create(article_params)
        new_article.novel_id = params[:novel_id] # Novel number that article belong to
        new_article.chapter = Article.chapter_number( params[:novel_id] )
        if new_article.save!
            Article.joins(new_article)
            redirect_to novel_path( params[:novel_id] )
        else
            @forms = Article.new
            @form_url = novel_articles_path
            render :new
        end
    end

    def show
        #byebug
        @novel = Novel.find( params[:novel_id] )
        @article = Article.where( "novel_id = ? and chapter = ?" , params[:novel_id] , params[:id] ).first
        @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    end

    def edit
        #byebug
        @forms = Article.where( "novel_id = ? and chapter = ?" , params[:novel_id] , params[:id] ).first
        @form_url = novel_article_path
    end
    def update
        article = Article.where( "novel_id = ? and chapter = ?" , params[:novel_id] , params[:id] ).first
        if article.update( article_params )
            redirect_to novel_article_path({ novel_id: params[:novel_id] , id: params[:id] })
        else
            render :new
        end
    end

    def destroy
        article = Article.where( "novel_id = ? and chapter = ?" , params[:novel_id] , params[:id] ).first
        article.destroy
        redirect_to novel_path( params[:novel_id] )
    end

    private
    def article_params
        params.require(:article).permit( :subtitle, :context )
    end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
    def new
        @forms = Novel.new
    end
    def create
        @new_novel = Novel.create(novel_params)
        @new_novel.author = current_user.email
        if @new_novel.save
            Novel.joins(@new_novel)
            redirect_to novels_path
        else
            render :new
        end
    end
    
    def index
        @novels = Novel.order("id DESC")
    end
    def show
        @novel = Novel.find( params[:id] )
        @articles = Article.where( "novel_id = ?" , params[:id] )
        @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    end

    def edit
        @forms = Novel.find(params[:id])
    end
    def update
        novel = Novel.find(params[:id])
        if novel.update(novel_params)
            redirect_to novel_path( Novel.find( params[:id] ) )
        else
            render :new
        end
    end

    def destroy
        novel = Novel.find(params[:id])
        novel.destroy
        articles = Article.where( "novel_id = ?" , params[:id] )
        articles.destroy_all
        redirect_to novels_path
    end

    private
    def novel_params
        params.require(:novel).permit( :title, :plot )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def novel_crud_member
        if user_signed_in?
            true
        else
            false
        end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def navi_arrow_link( novel_id , article_chapter , oprate_num )
        arrow_pos = oprate_num == 1 ? "ー＞" : "＜ー"
        chapter_going = article_chapter + oprate_num
        a = Article.where( "novel_id = ? and chapter = ?" , novel_id , chapter_going )
        if a.first != nil
            link_to arrow_pos, novel_article_path({ novel_id: novel_id , id: chapter_going }) , class:"section"
        end
    end

    def navi_calc( novel_id )
        all_article = Article.where( "novel_id = ?" , novel_id )
        return all_article.count
    end
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/views/articles/_form.html.erb
<%= form_for( @forms , url: @form_url, html:({class:"ts horizontal form"}) ) do |f| %>
    <div class="field">
        <%= f.label :subtitle , "小標題" %>
        <%= f.text_field :subtitle %>
    </div>
    <div class="field">
        <%= f.label :context , "內文" %>
        <%= f.text_area :context %>
    </div>
    <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<%= render "form" %>
<br />
<%= link_to "Back" , novel_article_path( @forms.novel_id, @forms.chapter ) %>

app/views/articles/new.html.erb
<%= render "form" %>
<br />
<%= link_to "回小說" , novel_path( params[:novel_id] ) %>

app/views/articles/show.html.erb
<h2><%= link_to @novel.title , novel_path( params[:novel_id] ) %></h2>
<h3><%= @article.subtitle %></h3>

<%= sanitize( @markdown.render( @article.context ) ) %>

<div id="navi_arrow">
    <%= navi_arrow_link( @novel.id , @article.chapter , -1 ) %>
    <span class="divdr"></span>
    <%= navi_arrow_link( @novel.id , @article.chapter , 1 ) %>
</div>

<%= content_for :footbar do %>
    <% if user_signed_in? %>
        <% if current_user.is_admin || current_user.email == @novel.author %>
            <%= link_to "編輯本章節", edit_novel_article_path({ novel_id: @novel.id , id: @article.chapter }) , class:"section" %>
            <div class="divider"> / </div>
            <%= link_to "刪除本章節", novel_article_path({ novel_id: @novel.id , id: @article.chapter }), data: {confirm: '確定嗎？'}, method: :delete , class:"section" %>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Novelist</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application' %>
    </head>
    <body class="ts container">
        <h1><%= link_to "成為小說家吧", novels_path %></h1>
        <%
            ts_class = "ts positive message" if notice
            ts_class = "ts negative message" if alert
        %>
        <div class="<%= ts_class %>">
            <%= notice if notice %>
            <%= alert  if alert  %>
        </div>

        <div class="ts divider"></div>
        <main>
            <%= yield %>
        </main>
        <div class="ts divider"></div>
        
        <footer>
            <div class="ts breadcrumb">
                <%= yield :footbar %>
            </div>
            <br />
            <div class="ts breadcrumb">
                <% if user_signed_in? %>
                    <%= link_to "登出", destroy_user_session_path, class:"section" , method: :delete %>
                <% else %>
                    <%= link_to "登入", new_user_session_path , class:"section" %>    
                <% end %>
            </div>
        </footer>
    </body>
</html>

app/views/novels/_footernav.html.erb
<%
navbar_compoments = {
    "index" : [],
    "show" : [],
    "edit" : []
}

member_services = {}
%>
<%= content_for :footbar do %>
<% end %>

app/views/novels/_form.html.erb
<%= form_for( @forms , html:({class:"ts horizontal form"}) ) do |f| %>
    <div class="field">
        <%= f.label :title , "標題" %>
        <%= f.text_field :title %>
    </div>
    <div class="field">
        <%= f.label :plot , "簡介" %>
        <%= f.text_area :plot %>
    </div>
    <%= f.submit %>
<% end %>

app/views/novels/edit.html.erb
<%= render "form" %>
<br />
<%= link_to "Back" , novel_path( @forms.id ) %>

app/views/novels/index.html.erb
<ul>
    <% @novels.each do |n| %>
    <li> <%= link_to n.title, novel_path(n.id) %> </li>
    <% end %>
</ul>

<%= content_for :footbar do %>
    <% if user_signed_in? %>
        <%= link_to "建立新的小說", new_novel_path , class:"section" %>
    <% end %>
<% end %>

app/views/novels/new.html.erb
<%= render "form" %>

app/views/novels/show.html.erb
<h2><%= @novel.title %></h2>

<%#= @markdown.render( @novel.plot ) %>
<%= sanitize( @markdown.render( @novel.plot ) ) %>

<ol>
    <% @articles.each do |a| %>
    <li><%= link_to a.subtitle , novel_article_path({ novel_id: @novel.id , id: a.chapter }) %></li>
    <% end %>
</ol>

<%= content_for :footbar do %>
    <% if user_signed_in? %>
        <% if current_user.is_admin || current_user.email == @novel.author %>
            <%= link_to "編輯大綱", edit_novel_path( @novel.id ) , class:"section" %>
            <div class="divider"> / </div>
            <%= link_to "刪除小說", novel_path( @novel.id ), data: {confirm: '確定嗎？'}, method: :delete , class:"section" %>
            <div class="divider"> / </div>
            <%= link_to "新的章節", new_novel_article_path( @novel.id ) , class:"section" %>
            <div class="divider"> / </div>
        <% end %>
    <% end %>
<% end %>